# This is a basic workflow to help you get started with Actions

name: CI
env:
  OCTOPUS_CLI_SERVER: https://srinivas.octopus.app/

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Run a one-line script
        run: |
          pwd
          ls -ltr
          tree

      - name: Install Octopus CLI
        uses: OctopusDeploy/install-octopus-cli-action@v1.1.9
        with:
          # Octopus CLI version
          version: # optional, default is latest
          
          
      - name: Push a package to Octopus Deploy 🐙
        uses: OctopusDeploy/push-package-action@v1.1.1
        with:
          api_key: API-IUDLNTKGAKKJYU2A4PVVIX5L9LXR72WA
          password: 
          packages: ../../aksdeploy
          server: 'https://srinivas.octopus.app/'
          username: 
          use_delta_compression: True
      - name: Create a release in Octopus Deploy
        uses: OctopusDeploy/create-release-action@v1.1.1
        with:
          api_key: API-IUDLNTKGAKKJYU2A4PVVIX5L9LXR72WA
          password: 
          project: 'firstProject'
          deploy_to: 'QA'
          server: 'https://srinivas.octopus.app/'
          username: 

  
